\documentclass{article}

\title{Fuzzy C Means}
\author{Daria Kopaliani}
\begin{document}
\maketitle

<<setup, include=FALSE, cache=FALSE>>=
opts_chunk$set(fig.path='figure/minimal-', fig.align='center', dev='pdf')
options(replace.assign=TRUE,width=90)
library(knitr)
library(ggvis)
source("fcm.R")
@

<<test, echo=FALSE, results=>>=

mtcars %>% ggvis(~wt, ~mpg, fill := "red") %>% layer_points()
@

\end{document}